#!/bin/bash

TEMPFILE=/tmp/rrdstats-`date +%s`-$RANDOM

while true;
do
   apachectl status > $TEMPFILE 2>/dev/null && break
   apache2ctl status > $TEMPFILE 2>/dev/null  && break
   /usr/sbin/apachectl status 2>/dev/null > $TEMPFILE && break
   /usr/sbin/apache2ctl status 2>/dev/null > $TEMPFILE && break
   rm -f $TEMPFILE
   exit 0 # no status available.
done

NR=`cat $TEMPFILE | grep -i "requests currently " | cut -f 1 -d'r'`
if test -z "$NR" ; then
	exit 0
fi

echo "services.apache.graph.title=Number of apache requests processed"
echo "services.apache.graph.unit=requests"
echo "services.apache.line.count.value=$NR"
echo "services.apache.line.count.type=GAUGE"

rm -f $TEMPFILE
