#!/usr/bin/perl -w
use strict;

my $data;
my $tmp;

open IFCONFIG, "/sbin/ifconfig -v|";
while(<IFCONFIG>) {
   /^([^\s]+)\s/ and $tmp = $1;
   /RX bytes:(\d+)/ and $data->{$tmp}->{in} = $1;
   /TX bytes:(\d+)/ and $data->{$tmp}->{out} = $1;
}
close IFCONFIG;

foreach my $if ( keys %{ $data } ) {
   my $in  = $data->{$if}->{in} ;
   my $out = $data->{$if}->{out} ;
   print "bandwidth.$if.graph.title = Bandwith usage for $if\n";
   print "bandwidth.$if.graph.unit  = Bytes/second\n";
   print "bandwidth.$if.line.in.label = Incoming bytes per second\n";
   print "bandwidth.$if.line.in.type  = COUNTER\n";
   print "bandwidth.$if.line.in.value = $in\n";
   print "bandwidth.$if.line.out.label = Outgoing bytes per second\n";
   print "bandwidth.$if.line.out.type  = COUNTER\n";
   print "bandwidth.$if.line.out.value = $out\n";
}
