#!/bin/bash

COUNT="$(( `/usr/sbin/postqueue -p | tail -1 | cut -d ' ' -f 5` ))"

echo "email.queuesize.graph.title=E-mail queue"
echo "email.queuesize.line.messages.value=$COUNT"
echo "email.queuesize.line.messages.type=GAUGE"
