#!/usr/bin/perl

my $s;

open STATS, "echo show status | mysql --host=localhost -N 2>&1|" ;

while(<STATS>) {
	/^ERROR/ and exit 0;
   my ($key,$value) = split /\s+/;
   $s->{$key} = $value;
}

print "services.mysql-connections.graph.title=Mysql Connections\n";
print "services.mysql-connections.graph.unit=New Connections/timeunit\n";
print "services.mysql-connections.line.connections.value=".$s->{Connections}."\n";
print "services.mysql-connections.line.connections.type=COUNTER\n";

print "services.mysql-queries.graph.title=Number of Mysql Queries\n";
print "services.mysql-queries.graph.unit=Number of queries\n";
foreach my $key ( qw/Com_insert Com_update Com_select Com_delete/ ) {
   print "services.mysql-queries.line.$key.value=".$s->{$key}."\n";
   print "services.mysql-queries.line.$key.type=COUNTER\n";
}
print "services.mysql-threads.graph.title=Mysql Threads\n";
print "services.mysql-threads.graph.unit=Number of Threads\n";
foreach my $key ( qw/Threads_connected Threads_cached Threads_running/ ) {
   print "services.mysql-threads.line.$key.value=".$s->{$key}."\n";
   print "services.mysql-threads.line.$key.type=GAUGE\n";
}
print "services.mysql-threads.line.Threads_created.value=".$s->{Threads_created}."\n";
print "services.mysql-threads.line.Threads_created.type=COUNTER\n";

close STATS;
