#! /bin/sh
# $Id: openfiles,v 1.3 2005/05/08 11:00:34 rjroos Exp $

SYSCTL=/sbin/sysctl

if test `uname` = "FreeBSD"
then
	OPENFILES=`$SYSCTL -n kern.openfiles`
	MAXFILES=`$SYSCTL -n kern.maxfiles`
else
	OPENFILES=`$SYSCTL -n fs.file-nr | cut -f 1`
	MAXFILES=`$SYSCTL -n fs.file-max`
fi

echo "system.openfiles.graph.title=Open filedescriptors"
echo "system.openfiles.line.openfiles.value=$OPENFILES"
echo "system.openfiles.line.openfiles.type=GAUGE"
echo "system.openfiles.line.maxfiles.value=$MAXFILES"
echo "system.openfiles.line.maxfiles.type=GAUGE"

