<?php
// generated by java 04-03-2014 15:10:15
if(!is_numeric($start)) {
	$start = time() - 24 * 3600 * 3;
}
$command = array();
$command[] = 'rrdtool';
$command[] = 'xport';
$command[] = '--json';
$command[] = '--start '.$start;
$parsedRrdDefs = array();
exec("/var/rrdstats/json/parserrddefs.py $computer $service", $parsedRrdDefs);
$command[] = join(' ', $parsedRrdDefs);
$command[] = '2>&1';
$cmd = join(' ', $command);
if(!isset($_REQUEST['debug'])) {
	header('Content-type: text/plain');
}
passthru($cmd);
?>
